### ISSUE TITLE
Kernel Error 

### ISSUE THREAD

**Issue by cwagenbach** [NSLS-II-CHX/CHX_BugReport#6]
Hi,
When I open a XPCS pipeline notebook to perform an analysis, I now get a Kernel Error. It does not matter which notebook I open, the error message remains. I have tried reconnecting to the kernel and restarting the kernel, but no improvement.  I have attached a screenshot of the kernel error. 

![kernel error](https://cloud.githubusercontent.com/assets/20478516/16878449/9851ba36-4a7a-11e6-9ec6-57588255760d.PNG)

When I click on the kernel error message, a popup box opens and says this: 
**Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/notebook/base/handlers.py", line 458, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/notebook/services/sessions/handlers.py", line 58, in post
    sm.create_session(path=path, kernel_name=kernel_name))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/notebook/services/sessions/sessionmanager.py", line 73, in create_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.4/dist-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/multikernelmanager.py", line 109, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/remotekernel/manager.py", line 60, in start_kernel
    """
AttributeError: 'KernelSpec' object has no attribute 'host'**

**Comment by yugangzhang** [comment]
We noticed that there was a Jupiterhub shut down yesterday without known reason. I met the same "no kernel" problem. I was suggested to restart the server snd the kernel works again.  So, please restart your sever.

**Comment by yugangzhang** [comment]
How to restart the server:

Click 'control panel' and restart 'my server'.

**Comment by cwagenbach** [comment]
Thanks, that fixed the problem.
